language: csharp
solution: Natasha.sln
dist: xenial
dotnet: 3.0.100
mono: none

branches:
  only:
  - master

os:
  - linux
  - osx

osx_image: xcode9.1
before-script:
- sudo apt-get install dotnet-sdk-2.2

script:
 - export PATH="$PATH:$HOME/.dotnet/tools"
 - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
 - flubu Rebuild.Server -apiKey=${Nuget_Api_Key}
